services:
  auth:
    build:
      dockerfile: auth/Dockerfile
    environment:
      HOST: ${AUTH_SERVICE_SERVER_HOST}
      PORT: ${AUTH_SERVICE_PORT}
      DB_HOST: ${AUTH_DB_HOST}
      DB_PORT: ${AUTH_DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - auth-db
      - redis

  auth-db:
    image: mongo:latest

  account:
    build:
      dockerfile: account/Dockerfile
    environment:
      HOST: ${ACCOUNT_SERVICE_SERVER_HOST}
      PORT: ${ACCOUNT_SERVICE_PORT}
      DB_HOST: ${ACCOUNT_DB_HOST}
      DB_PORT: ${ACCOUNT_DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - account-db
      - redis

  account-db:
    image: mongo:latest

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}

  api-gateway:
    build:
      dockerfile: api-gateway/Dockerfile
    ports:
      - 80:${API_GATEWAY_SERVICE_PORT}
    environment:
      API_GATEWAY_SERVICE_PORT: ${API_GATEWAY_SERVICE_PORT}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_CLIENT_HOST}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      ACCOUNT_SERVICE_HOST: ${ACCOUNT_SERVICE_CLIENT_HOST}
      ACCOUNT_SERVICE_PORT: ${ACCOUNT_SERVICE_PORT}
    depends_on:
      - auth
      - account